### ISSUE TITLE
Definindo motor do site. "Manual" ou Jekyll

### ISSUE THREAD

**Issue by halcance** [mozillabrasil/mozillabrasil.github.io#1]
Para o motor do site, temos duas boas opções, na qual vocês podem dar outras alternativas.
- Jekyll
- Criar um site estático criando cada página manualmente.

**Comment by torto** [comment]
Acho que a pergunta que devemos nos perguntar, se ele vai ser tpw blog ou ter muitas páginas diferentes.. 
Pq se for muito dinâmico melhor opção é usar algo estático, caso contrário, Jekyll eh uma ótima opção :heart: :dancers:

**Comment by cpswsg** [comment]
Acho importante linkar o [tópico no discourse](https://discourse.mozilla-community.org/t/retorno-da-reuniao-sobre-o-novo-site-da-comunidade/10061/6) que aborda esse tema.

**Comment by halcance** [comment]
@cynthiapereira acho que não seria bem necessário já que este é o site da Mozilla no Github assim como twitter.github.io / microsoft.github.io etc, sendo um site independente para que possamos interagir com a web em si. Apenas quem deseja contribuir com este pequeno projeto.

**Comment by halcance** [comment]
@torto Jekyll seria melhor, assim criamos o conteúdo apenas em markdown sem a necessidade de criar novos styles, layouts, css, etc.

**Comment by torto** [comment]
Existe a necessidade de um blog no nosso mozilabrasil.github.io?
Qual a finalidade do nosso .io?

**Comment by halcance** [comment]
Estava pensando na criação de tipo um blog, além de promover a Mozilla e seus produtos, defender a web aberta, tópicos sobre Linux, programas alternativos, exemplo substituindo o Microsoft Office pelo LibreOffice, seria ótimo nos envolvermos com o público, inclusive irei discutir esse projeto com a comunidade mozilla :)

**Comment by halcance** [comment]
@cynthiapereira  o que acha ?

**Comment by torto** [comment]
@alipseight entendo sua motivação de criar esse github.io, mas precisamos ter certeza que isso é algo que realmente se faz necessário para Mozilla, pq se criarmos algo que não podemos dar manutenção do que vai adiantar fazer?
Acho que precisamos criar realmente a discussão se isso eh realmente necessário, caso for a comunidade vai poder dar manutenção nele, pq se não me engano nos já temos um blog e ele não é alimentado.
Compreende q eu quero dizer?

**Comment by torto** [comment]
Outra coisa, não faça merge sem validação de outros usuários.

**Comment by halcance** [comment]
@torto  sim, o bog pelo que eu vi é mais para anúncios da comunidade, já o github seria um projeto grátis (Hospedado pelo gh-pages), Open Source (Códigos, textos, além de issues da comunidade), e que todos poderiam dar sua opinião, contribuir e interagir.

**Comment by halcance** [comment]
Sim, mas esses merge foi para algo que já estava no site, apenas organizei em pastas e criei um arquivo para dar inicio ao CSS responsivo. Não foi criado conteúdo.

**Comment by torto** [comment]
@alipseight todo e qualquer projeto da Mozilla tem q ser Open Source, todo projeto podemos dar nossa opinião, contribuir e interagir. Nosso blog ele eh "grátis" pq fica no servidor da própria Mozilla.
O ponto que gostaria de ressaltar, é:
- Qual a finalidade desse blog? 
- Oque ele faz que o outro não faz? 
- Pq a comunidade precisa ter dois blog?
- Quem vai manter esse blog?
- Pq existir dois blogs se podemos categorizar o outro?

**Obs:** A Mozilla tem um styleguide para layouts de sites, não se pode mudar muito do que já tem definido :dancers:

**Comment by halcance** [comment]
Estou planejando algo aqui que irei postar no discourse que vai incluir e definir o propósito deste site.

**Comment by halcance** [comment]
Fechando
