### ISSUE TITLE
Levantamento de Contribuidores

### ISSUE THREAD

**Issue by halcance** [mozillabrasil/mozillabrasil.github.io#3]
Os interessados em contribuir com o mozillabrasil.github.io deixem aqui um "ólá" para sabermos a quantidade de usuários.

Os interessados já podem discutir neste tópico https://github.com/mozillabrasil/mozillabrasil.github.io/issues/1  como irá funcionar o site.

**Comment by torto** [comment]
tamo na atividade!

**Comment by halcance** [comment]
Fechando
